services:
  website-ae:
    build: 
      context: .
      target: dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - .:/app
      - /app/node_modules

  website-ae-prod:
    build: 
      context: .
      target: prod
      args:
        - AE_VARS_METHOD=dotenv
        - AE_DOTENV_FILE=.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge