/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    person: Person;
    material: Material;
    sportsTeam: SportsTeam;
    sponsor: Sponsor;
    association: Association;
    studentGuide: StudentGuide;
    link: Link;
    position: Position;
    board_section: BoardSection;
    president: President;
    spaceData: SpaceDatum;
    video: Video;
    faq: Faq;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "person".
 */
export interface Person {
  id: number;
  name: string;
  position: number | Position;
  photo?: (number | null) | Media;
  description?: string | null;
  birthday?: string | null;
  socials?:
    | {
        type: 'linkedin' | 'facebook' | 'website' | 'instagram';
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "position".
 */
export interface Position {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material".
 */
export interface Material {
  id: number;
  name: string;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sportsTeam".
 */
export interface SportsTeam {
  id: number;
  sport_name: string;
  fap_id?: number | null;
  coach?: (number | null) | Person;
  workouts?:
    | {
        weekDay: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        hour: string;
        id?: string | null;
      }[]
    | null;
  emoji?:
    | (
        | '⚽️'
        | '🏀'
        | '🏈'
        | '🎾'
        | '🏐'
        | '🏉'
        | '🥏'
        | '🏓'
        | '🏸'
        | '🏒'
        | '🏑'
        | '🏏'
        | '🥍'
        | '🥅'
        | '🎱'
        | '🏹'
        | '🎿'
        | '🛷'
        | '🚴‍♂️'
        | '🏄‍♂️'
        | '🏇'
        | '🏊‍♂️'
        | '🏋️‍♂️'
        | '🤼‍♂️'
        | '🤸‍♂️'
        | '🤺'
        | '🤾‍♂️'
        | '🏌️‍♂️'
        | '🧗‍♂️'
        | '🚣‍♂️'
        | '🚵‍♂️'
        | '🏎️'
        | '🏍️'
      )
    | null;
  lineup?:
    | {
        lineupRow?:
          | {
              person: number | Person;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  backgroundImage: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsor".
 */
export interface Sponsor {
  id: number;
  name: string;
  url: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "association".
 */
export interface Association {
  id: number;
  name: string;
  in_aefeup: boolean;
  description?: string | null;
  logo: number | Media;
  address?: string | null;
  socials?:
    | {
        type: 'website' | 'linkedin' | 'facebook' | 'instagram';
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentGuide".
 */
export interface StudentGuide {
  id: number;
  language: 'Português' | 'Inglês';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link".
 */
export interface Link {
  id: number;
  label: string;
  url: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board_section".
 */
export interface BoardSection {
  id: number;
  name: string;
  members: {
    person: number | Person;
    id?: string | null;
  }[];
  description?: string | null;
  subgroups?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "president".
 */
export interface President {
  id: number;
  name: string;
  photo?: (number | null) | Media;
  start_year: number;
  end_year: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaceData".
 */
export interface SpaceDatum {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video".
 */
export interface Video {
  id: number;
  título: string;
  thumbnail?: number | Media | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
 /**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  quest: string;
  ans: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}